################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
#################################################################################
import json
import sys
from pathlib import Path

from flink_agents.plan.agent_plan import AgentPlan
from flink_agents.plan.function import JavaFunction

# The java agent plan json to be checked is generated by
# flink-agents/plan/src/test/java/org/apache/flink/agents/plan/
# compatibility/GenerateAgentPlanJson.java
if __name__ == "__main__":
    json_path = sys.argv[1]
    with Path.open(Path(json_path)) as f:
        java_plan_json = f.read()

    raw_agent_plan = json.loads(java_plan_json)
    agent_plan = AgentPlan.model_validate_json(java_plan_json)
    actions = agent_plan.actions

    assert len(actions) == 5

    event = "org.apache.flink.agents.api.Event"
    input_event = "_input_event"
    my_event = "MyEvent"
    runner_context = "org.apache.flink.agents.api.context.RunnerContext"
    qualname = "org.apache.flink.agents.plan.compatibility.GenerateAgentPlanJson$JavaAgentPlanCompatibilityTestAgent"

    # check the first action
    assert "firstAction" in actions
    action1 = actions["firstAction"]
    func1 = action1.exec
    assert isinstance(func1, JavaFunction)
    assert func1.qualname == qualname
    assert func1.method_name == "firstAction"
    assert func1.parameter_types == [
        event,
        runner_context,
    ]
    trigger_conditions1 = action1.trigger_conditions
    assert trigger_conditions1 == [input_event]

    # check the second action
    assert "secondAction" in actions
    action2 = actions["secondAction"]
    func2 = action2.exec
    assert isinstance(func2, JavaFunction)
    assert func2.qualname == qualname
    assert func2.method_name == "secondAction"
    assert func2.parameter_types == [
        event,
        runner_context,
    ]
    trigger_conditions2 = action2.trigger_conditions
    assert sorted(trigger_conditions2) == [
        my_event,
        input_event,
    ]

    # Runtime indexes are derived after plan loading and are not part of the
    # wire format.
    assert "actions_by_event" not in raw_agent_plan

    # check Java tool parameter injection survives agent plan JSON
    raw_tool_providers = raw_agent_plan["resource_providers"].get(
        "tool", raw_agent_plan["resource_providers"].get("TOOL")
    )
    raw_tool_provider = raw_tool_providers["add"]
    serialized_tool = json.loads(raw_tool_provider["serializedResource"])
    input_schema = json.loads(serialized_tool["metadata"]["inputSchema"])
    assert set(input_schema["properties"]) == {"a", "b"}
    assert "tenant_id" not in input_schema["properties"]
    assert serialized_tool["injected_args"] == {
        "tenant_id": {"source": "config", "key": "tenant.id"}
    }
