/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.agents.api;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Map;
import java.util.UUID;

/** Event generated by the framework, carrying an input data that arrives at the agent. */
public class InputEvent extends Event {

    public static final String EVENT_TYPE = "_input_event";

    public InputEvent(Object input) {
        super(EVENT_TYPE);
        setAttr("input", input);
    }

    @JsonCreator
    public InputEvent(
            @JsonProperty("id") UUID id,
            @JsonProperty("attributes") Map<String, Object> attributes) {
        super(id, EVENT_TYPE, attributes);
    }

    /**
     * Reconstructs a typed InputEvent from a base Event.
     *
     * @param event the base event containing the input data in attributes
     * @return a typed InputEvent
     */
    public static InputEvent fromEvent(Event event) {
        return reconstructFrom(event, InputEvent::new);
    }

    @JsonIgnore
    public Object getInput() {
        return getAttr("input");
    }
}
